1.  Numpy is a python library which is used to work with arrays.

2.  It also has functions for working in domain of linear algebra , fourier transform , and matrics.

In [3]:
pip install numpy


In [50]:
import numpy
arr = numpy.array([1,2,3,4,5])
print(arr)


[1 2 3 4 5]


In [52]:
import numpy as np  # It is alias
arr = np.array([1,2,3,4,5])
print(arr)


[1 2 3 4 5]


In [54]:
type(arr)

numpy.ndarray

In [55]:
arr = np.array([43]) # 0 Dimensional array bcoz of 1 element
print(arr)
type(arr)

[43]


numpy.ndarray

In [57]:
arr = np.array([1,2,3,4,5,6]) # 1 Dimensional array bcoz of more than 1 element
print(arr)

[1 2 3 4 5 6]


In [59]:
arr = np.array([[1,2,3],[4,5,6]]) # 2 Dimensional array bcoz of more than 1 element in 2 frames
print(arr)

[[1 2 3]
 [4 5 6]]


In [61]:
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]]]) # 3 Dimensional array bcoz of more than 1 element in 3 frames
print(arr)
print("Array Dimension -",arr.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
Array Dimension - 3


In [64]:
 arr = np.array([1,2,3,4],ndmin = 32) # ndmin is used for give the dimension by user
print(arr)
print("Dimensions:" , arr.ndim)

[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[1 2 3 4]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]
Dimensions: 32


In [66]:
 arr = np.array([1,2,3,4],ndmin = 0) # ndmin is used for give the dimension by user
print(arr)
print("Dimensions:" , arr.ndim)

# it will give 1D because more than one element

[1 2 3 4]
Dimensions: 1


In [68]:
arr = np.array([1,2,3,4,56,6])
print(arr[4])

# It is working as give the element on the given index number

56


In [70]:
arr = np.array([[1,2,3],[4,5,6]]) # 2 Dimensional array bcoz of more than 1 element
print(arr[0,1])

2


In [72]:
 arr = np.array([[[1,2,3],[4,5,6],[7,8,9]]]) # 3 Dimensional array bcoz of more than 1 element
print(arr[0,1,1])

5


In [74]:
 arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]) # 3 Dimensional array bcoz of more than 1 element
print(arr[1,0,1])

8


In [76]:
arr = np.array([1,2,3,4,5,6])   # Slicing
print(arr[1:4])

[2 3 4]


In [78]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])   # Slicing
print(arr[1:9:3])

[2 5 8]


In [97]:
arr = np.array ([[1,2,3,4,5],[6,7,8,9,10]])

print(arr[0, 0:4])
print(arr[1, 1:3])

[1 2 3 4]
[7 8]


Shape of an array the shape of an array is the number of elements in each dimension.

In [114]:
arr = np.array([[1,2,3] , [4,5,6]]) # 2 dimension and 3 elements in it

print(arr.shape)

(2, 3)


Reshapping Array - change the shape of an array. The shape of an array is the number of elements in each Dimension

In [124]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [132]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [134]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
for x in arr:
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12


In [138]:
arr = np.array([[1,2,3,4],[7,8,9,10]])
for x in arr:
    print(x)

[1 2 3 4]
[ 7  8  9 10]


Joining Arrays - joining means puting contents of two or more array in a single array.


In [145]:
arr1 = np.array([1,2,3])   # concatenate means merge the values
arr2 = np.array([4,5,6])
arr = np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]
